# Generated by Django 3.1.1 on 2020-09-27 12:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=20)),
                ('trends', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=128)),
                ('category', models.CharField(max_length=20)),
                ('images', models.ImageField(default='', upload_to='images/blog')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
