# Generated by Django 3.1.1 on 2020-10-01 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('objective', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('scope', models.CharField(choices=[('rural', 'rural'), ('urban', 'urban'), ('national', 'national'), ('international', 'international')], max_length=30)),
                ('reg_no', models.IntegerField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('contribution', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('turnover', models.IntegerField()),
                ('pollution', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('sustainibility', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('csr_def', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('plant', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('untreated_sewage', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('emp_month', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('env_audit', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('garbage', models.CharField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('employment', models.CharField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('health', models.CharField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('recycle', models.CharField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('responsibility', models.CharField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('energy', models.CharField(choices=[('conventional', 'conventional'), ('non_conventional', 'non_conventional'), ('mix', 'mix')], max_length=35)),
                ('water_source', models.CharField(choices=[('River/lake', 'River/lake'), ('Ground water', 'Ground water'), ('Rain water', 'Rain water'), ('Municipal water', 'Municipal water')], max_length=35)),
                ('effluent', models.CharField(choices=[('air', 'air'), ('water', 'water'), ('soil', 'soil'), ('not_applied', 'not_applied')], max_length=35)),
                ('effluent_q', models.CharField(choices=[('>50%', '>50%'), ('30%', '30%'), ('20%', '20%'), ('5%', '5%'), ('1%', '1%')], max_length=35)),
                ('nature_waste', models.CharField(choices=[('recyclabe', 'recyclabe'), ('non_recyclabe', 'non_recyclabe'), ('partial_recyclable', 'partial_recyclable'), ('nearly_null', 'nearly_null')], max_length=35)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_cap', models.IntegerField(default=0)),
                ('member', models.IntegerField(default=0)),
                ('garbage', models.TextField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=30)),
                ('waste_water', models.TextField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=30)),
                ('biodegradable', models.TextField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=30)),
                ('recycle', models.TextField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('govt', models.TextField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('disposal', models.TextField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('energy', models.TextField(choices=[('not at all', 'not at all'), ('to some extent', 'to some extent'), ('a lot', 'a lot')], max_length=35)),
                ('bulb', models.TextField(choices=[('yes', 'yes'), ('no', 'no')], max_length=30)),
                ('cfc', models.TextField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('news', models.TextField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('plant', models.TextField(choices=[('yes', 'yes'), ('no', 'no')], max_length=35)),
                ('travel', models.TextField(choices=[('public', 'public'), ('private', 'private'), ('carpool', 'carpool')], max_length=30)),
                ('diet', models.TextField(choices=[('veg', 'veg'), ('non_veg', 'non_veg'), ('mostly veg', 'mostly veg')], max_length=35)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
