# Generated by Django 3.1.1 on 2020-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsurvey',
            name='aluminium',
            field=models.CharField(choices=[('option1', 'Yes'), ('option2', 'No'), ('option3', 'Yes'), ('option4', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mainsurvey',
            name='newspaper',
            field=models.CharField(choices=[('option1', 'Yes'), ('option2', 'No'), ('option3', 'Yes'), ('option4', 'No')], max_length=10),
        ),
    ]
