# Generated by Django 3.1.1 on 2020-09-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsurvey',
            name='car',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mainsurvey',
            name='electric',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mainsurvey',
            name='flights',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mainsurvey',
            name='gas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mainsurvey',
            name='oil',
            field=models.IntegerField(),
        ),
    ]
